# Information about the namespace.
information:
  # Organisational information.
  division: "TEST"
  team: "The Test Team"
  projectName: "TestingSolutions"
  projectLead: "Test Tester"
  # The priority of the workload. Can be critical or medium.
  priority: "critical"
  technicalLead: "Tester Test"
  # The Jira ticket ID of the Epic used to onboard the project.
  onboardingEpic: "TEST-1234"
  # The location of the signed authority to operate.
  authorityToOperate: "gcdocs.gc.ca/ssc-spc/example"

  # Information about tooling.
  gitGroupURL: "gitlab.example/test"

  # Financial and organizational identifiers.
  FRC: 0001
  PE: 001
  workloadID: 0000001
  productID: 00001

# Configurations about the namespace.
namespace:
 # Extra labels to add to the namespace.
  labels: {}
  # The type of namespace.
  # Can be one of [gateway, solution, system].
  type: "argocd-control-plane"

# Policy configurations on the namespace.
policies:
  # List of host/path that can be exposed from the namespace.
  allowedHosts:
    - www.example.ca/service
    - www.example.ca/
    - www.example.ca
  # Boolean which defines if the namespace should have Istio injection.
  istioInjection: true

# Define AAD Pod Identity information.
aadPodIdentities:
  test-production-mi:
    clientID: "11111111-1111-1111-1111-111111111111"
    resourceID: "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-production-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-production-mi"

# Defines the access control on the namespace.
# Roles will be assigned based on the namespace type.
rbac:
  groups: ["testers"]

# Defines resource quotas on the namespace.
resourceQuotas:
  # The maximum number of pods that can be in the namespace.
  pods: 60
  # Quotas related to services and external traffic.
  services:
    # The maximum number of loadbalancers that can be configured.
    loadbalancers: 0
    # The maximum number of NodePorts that can be configured.
    nodeports: 0
  # The upper limit of storage that can be requested across all persistent volumes.
  # Expects a string value of a number with or without units (uses SI units).
  storage: ''

argocdProject:
  namespace: "platform-solution-system"
  destination:
    namespace: "test"

  sourceRepos: ["*"]
  developerGroups: []            # defaults to rbac.groups if empty
  adminGroups: ["testers"]       # defaults to rbac.groups if empty
