{{ if .Values.components.kubebench.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-kube-bench"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "kube-bench" .Values.components.kubebench.helm.chart }}
    {{- if .Values.global.helm.repository }}
    repoURL:  repoURL: {{ default "oci://ghcr.io/deliveryhero/helm-charts/kube-bench" .Values.global.helm.repository }}
    {{- else }}
    repoURL: {{ default "https://kube-bench.github.io/cost-analyzer/" .Values.components.kubebench.helm.repository }}
    {{- end }}
    targetRevision: {{ default "1.106.0" .Values.components.kubebench.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "kube-bench"
        - name: HELM_VALUES
          value: |
            global:
              imagePullSecrets: {{ toYaml .Values.components.kubebench.imagePullSecrets | nindent 14 }}

  destination:
    name: {{ .Values.global.cluster }}
    namespace: kube-bench-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
