{{ if .Values.components.trustManager.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-trust-manager"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "trust-manager" .Values.components.trustManager.helm.chart }}
    {{- if .Values.components.trustManager.helm.repository }}
    repoURL: {{ .Values.components.trustManager.helm.repository }}
    {{- else }}
    repoURL: {{ default "https://charts.jetstack.io" .Values.global.helm.repository }}
    {{- end }}
    targetRevision: {{ default "v0.21.1" .Values.components.trustManager.helm.targetRevision }}
    helm:
      releaseName: trust-manager
      values: |
        crds: 
          enabled: true

        image: {{ default "{}" (include "trustManager.image" .) | nindent 10 }}
        imagePullSecrets: {{ toYaml .Values.components.trustManager.imagePullSecrets | nindent 12 }}
        
        replicaCount: {{ .Values.components.trustManager.replicas }}
        resources: {{ toYaml .Values.components.trustManager.resources | nindent 10 }}
        nodeSelector: {{ toYaml .Values.components.trustManager.nodeSelector | nindent 10 }}
        tolerations: {{ toYaml .Values.components.trustManager.tolerations | nindent 10 }}
        affinity: {{ toYaml .Values.components.trustManager.affinity | nindent 10 }}
        priorityClassName: {{ .Values.components.trustManager.priorityClassName }}

        app:
          trust:
            namespace: cert-manager-system

        defaultPackage:
          resources: {{ toYaml .Values.components.trustManager.defaultPackage.resources | nindent 12 }}
        defaultPackageImage: {{ default "{}" (include "trustManager.defaultPackage.image" .) | nindent 10 }}

  destination:
    name: {{ .Values.global.cluster }}
    namespace: trust-manager-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
