{{- if (or (gt (len .Values.rbac.securityOperations.groups) 0) (gt (len .Values.rbac.securityOperations.users) 0)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-rbac-security-operations"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: rbac-security-operations
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: security-operations
              annotations:
                kubernetes.io/description: |-
                  Binding to the view role
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: view
            subjects:
              {{- range .Values.rbac.securityOperations.groups }}
              - apiGroup: rbac.authorization.k8s.io
                kind: Group
                name: {{ . }}
              {{- end }}
              {{- range .Values.rbac.securityOperations.users }}
              - apiGroup: rbac.authorization.k8s.io
                kind: User
                name: {{ . }}
              {{- end }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
