global:
  helm: {}
    # Override all Helm applications to pull
    # their helm chart from the following
    # repository.
    #
    # You can override specific charts below
    # in the components section.
    # repository: https://myrepo.example.ca

  container: {}
    # Override all applications to pull
    # their container from the following
    # registry.
    #
    # You can override specific charts below
    # in the components section.
    # registry: docker.io

  namespace:
    helm:
      chart:
      targetRevision:
      repository:

  raw:
    helm:
      chart:
      targetRevision:
      repository:

  # Cluster name for the Application targets.
  cluster: in-cluster

  # Which project to place applications in.
  project: aurora-app

  # Ingress Domain
  ingressDomain: example.ca

  # Ingress Class Name
  # ingressClassName: ingress-istio-controller

  # The Azure subscription ID used for the cluster
  # subscriptionId: ""

  # The Azure tenant ID used for the cluster
  # tenantId: ""

  # Load Balancer Subnet Name for all Load Balancers
  # load_balancer_subnet_name: ""

data:
  mgmt:
    enabled: true

# Components
components:
  argoFoundation:

    argocdInstance:
      helm: {}
      # chart: argocd-instance
      # repository: https://gccloudone-aurora.github.io/aurora-platform-charts
      # targetRevision: 0.0.6

      # disableAdmin: true
      # ingressDomain: ""

      nodeSelector:
        kubernetes.io/os: linux
        node.ssc-spc.gc.ca/purpose: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists

      argocdVaultPlugin:
        credentials: {}
      #     azureTenantID: ""
      #     azureClientID: ""
      #     azureClientSecret: ""

      oidcAuthSP:
        credentials: {}
      #     tenantID: ""
      #     clientID: ""
      #     clientSecret: ""

      aadPodIdentity: {}
        # enabled: false

      netpol: {}
        # enabled: false

      notifications: {}
        # enabled: false

      server:
        service: {}
          # type: ""

      repo:
        resources: {}
          # limits:
          #   cpu: ""
          #   memory: ""
          # requests:
          #   cpu: ""
          #   memory: ""

      controller:
        resources: {}
          # limits:
          #   cpu: ""
          #   memory: ""
          # requests:
          #   cpu: ""
          #   memory: ""
      applicationSet:
        resources: {}
          # limits:
          #   cpu: ""
          #   memory: ""
          # requests:
          #   cpu: ""
          #   memory: ""

      redis:
        resources: {}
          # limits:
          #   cpu: ""
          #   memory: ""
          # requests:
          #   cpu: ""
          #   memory: ""

      register:
        clusters: {}
        repositories: {}
        repositoryCreds: {}

    argocdProjects:
      platform:
        # applicationSet:
        #   generator:
        #     git:
        #       repoURL
        #       revision
        #       files:
        #   template:
        #     source:
        #       repoURL

      solutions:
        # applicationSet:
        #   generator:
        #     git:
        #       repoURL
        #       revision
        #       files:
        #   template:
        #     source:
        #       repoURL

      syncWindows:
        - clusters:
            - '*'
          duration: 5h
          kind: allow
          manualSync: true
          schedule: '* 19 * * 2,4'
          timeZone: America/Toronto

  argoOperator:
    helm: {}
      # chart: argocd-operator
      # repository: https://gccloudone-aurora.github.io/aurora-platform-charts
      # targetRevision: 0.4.1

    imagePullSecrets: []
    image:
      # registry: quay.io
      repository: argoprojlabs/argocd-operator
      tag: "v0.4.0"
      # pullPolicy: IfNotPresent

    priorityClassName: platform-cluster-medium

    replicas: 1
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""
    nodeSelector:
      kubernetes.io/os: linux
      node.ssc-spc.gc.ca/purpose: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    affinity: {}

  billOfLanding:
    enabled: true

    helm: {}
      # chart: bol
      # repository: https://gccloudone-aurora.github.io/aurora-platform-charts
      # targetRevision: 0.0.1

    image:
      # registry: docker.io
      repository: bol
      # tag: v0.0.1

    nodeSelector:
      kubernetes.io/os: linux
      node.ssc-spc.gc.ca/purpose: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

    config:
      artifactRepository: {}
        # provider: azure
        # azure:
        #   storageAccountName: <storage-account-name>
        #   storageAccountContainerName: <container-name>
        #   useAzureCliCredentials: false

      clusters: []
        # - name:
        #   subscription:
        #   kubecostURL:
        #   kubernetesAuth:
        #     method: manual
        #     manual:
        #       host:
        #       bearerToken:
        #       tlsClientConfig:
        #         insecure: true
        #         caData:

      # fileNameSuffix: ""
      # maximumReportingWindowInDays: 30

    aadPodIdentity:
      azureManagedIdentity: {}
        # clientId:
        # resourceId:

rbac:
  # Groups and users that should be bound to the platform-admin role.
  # Note: if using AKS with AAD enabled, this is not necessary since admins
  #       will be defined in the configuration.
  platformAdmin:
    groups: []
    users: []
  # Configurations for the platform-operator-daily role.
  # A read-only aggregated role which uses the
  # 'rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-view: "true"'
  # label as the selector.
  platformOperator:
    groups: []
    users: []
