{{ if and .Values.components.certManager.enabled .Values.components.certManager.aadPodIdentity.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-cert-manager-aad-pod-identity"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "cert-manager-manifests"
        - name: HELM_VALUES
          value: |
            resources:
              - apiVersion: "aadpodidentity.k8s.io/v1"
                kind: AzureIdentity
                metadata:
                  name: {{ .Values.components.certManager.aadPodIdentity.name }}
                  namespace: cert-manager-system
                  labels:
                    app.kubernetes.io/name: "cert-manager-manifests"
                    app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                    app.kubernetes.io/component: auth
                    app.kubernetes.io/part-of: cert-manager-system
                    app.kubernetes.io/managed-by: argo
                    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
                  annotations:
                    aadpodidentity.k8s.io/Behavior: "namespaced"
                spec:
                  clientID: {{ required "certManager.aadPodIdentity.azureManagedIdentity.clientId is required" .Values.components.certManager.aadPodIdentity.azureManagedIdentity.clientId | quote }}
                  resourceID: {{ required "certManager.aadPodIdentity.azureManagedIdentity.resourceId is required" .Values.components.certManager.aadPodIdentity.azureManagedIdentity.resourceId | quote }}
                  type: 0
              - apiVersion: "aadpodidentity.k8s.io/v1"
                kind: AzureIdentityBinding
                metadata:
                  name: {{ .Values.components.certManager.aadPodIdentity.name }}
                  namespace: cert-manager-system
                  labels:
                    app.kubernetes.io/name: "cert-manager-manifests"
                    app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                    app.kubernetes.io/component: auth
                    app.kubernetes.io/part-of: cert-manager-system
                    app.kubernetes.io/managed-by: argo
                    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
                spec:
                  azureIdentity: {{ .Values.components.certManager.aadPodIdentity.name }}
                  selector: {{ .Values.components.certManager.aadPodIdentity.name }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
