{{ if .Values.components.trivy.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-trivy"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "trivy-operator" .Values.components.trivy.helm.chart }}
    {{- if .Values.components.trivy.helm.repository}}
    repoURL: {{ .Values.components.trivy.helm.repository }}
    {{- else }}
    repoURL: {{ default "https://aquasecurity.github.io/helm-charts" .Values.global.helm.repository }}
    {{- end }}
    targetRevision: {{ default "0.31.0" .Values.components.trivy.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "trivy-operator"
        - name: HELM_VALUES
          value: |
            affinity: {{ toYaml .Values.components.trivy.affinity | nindent 14 }}
            image: {{ default "{}" (include "trivy.image" .) | nindent 14 }}
            nodeSelector: {{ toYaml .Values.components.trivy.nodeSelector | nindent 14 }}
            operator: {{ toYaml .Values.components.trivy.operator | nindent 14 }}
            priorityClassName: {{ .Values.components.trivy.priorityClassName }}
            resources: {{ toYaml .Values.components.trivy.resources | nindent 14 }}
            serviceMonitor:
              enabled: true
            targetWorkloads: {{ .Values.components.trivy.targetWorkloads }}
            tolerations: {{ toYaml .Values.components.trivy.tolerations | nindent 14 }}
            trivy:
              builtInTrivyServer: {{ .Values.components.trivy.builtInTrivyServer }}
              severity: {{ .Values.components.trivy.severity }}
            excludeNamespaces: {{ .Values.components.trivy.excludeNamespaces | quote }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
