# Information about the namespace.
information:
  # Organisational information.
  division: "TEST"
  team: "The Test Team"
  projectName: "TestingSolutions"
  projectLead: "Test Tester"
  # The priority of the workload. Can be critical or medium.
  priority: "critical"
  technicalLead: "Tester Test"
  # The Jira ticket ID of the Epic used to onboard the project.
  onboardingEpic: "TEST-1234"
  # The link to the authority to operate.
  authorityToOperate: "gcdocs.gc.ca/ssc-spc/example"

  # Information about tooling.
  gitGroupURL: "gitlab.example/test"

  # Financial and organizational identifiers.
  FRC: 0001
  PE: 001
  workloadID: 0000001
  productID: 00001

# Configurations about the namespace.
namespace:
 # Extra labels to add to the namespace.
  labels: {}
  # The type of namespace.
  # Can be one of [gateway, solution, system].
  type: "solution"
  # Can be one of [argocd, none].
  deploymentMethod: "argocd"

# Policy configurations on the namespace.
policies:
  # List of host/path that can be exposed from the namespace.
  allowedHosts:
    - www.example.ca/service
    - www.example.ca/
    - www.example.ca
  # Boolean which defines if the namespace should have Istio injection.
  istioInjection: true

# Defines the access control on the namespace.
# Roles will be assigned based on the namespace type.
rbac:
  groups: ["testers"]

# Defines resource quotas on the namespace.
resourceQuotas:
  # The maximum number of pods that can be in the namespace.
  pods: 60
  # Quotas related to services and external traffic.
  services:
    # The maximum number of loadbalancers that can be configured.
    loadbalancers: 0
    # The maximum number of NodePorts that can be configured.
    nodeports: 0
  # The upper limit of storage that can be requested across all persistent volumes.
  # Expects a string value of a number with or without units (uses SI units).
  storage: '0'

argocd:
  project:
    adminGroups:
      - "admin-1"
      - "admin-2"

clusters:
  gen-dev-cc-00: {}
  gen-test-cc-00: {}
  gen-uat-cc-00: {}
  gen-qa-cc-00: {}
  gen-prod-cc-00: {}
