argocdInstance:

  applicationInstanceLabelKey: "platform.ssc-spc.gc.ca/application-name"

  disableAdmin: false

  ingressDomain: ""

  logLevel: "info"

  oidcAuthSP:
    tenantID: ""
    clientID: ""
    clientSecret: ""

  sourceNamespaces: []

  globalProjects: []
    # - projectName: "global"
    #   labelSelector:
    #     key: "argocd.argoproj.io/project-inherit"
    #     value: "global"

  # installationID: ""


  ##### Components #####

  imageRegistry:
    host: "quay.io"
    repository: ""

  image:
    name: "argoproj/argocd"
    version: "v3.2.1"

  nodeSelector: {}
  tolerations: []

  applicationSet:
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""

  controller:
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""

  notifications:
    enabled: false

  redis:
    imageRegistry:
      host: "docker.io"
      repository: ""

    image:
      name: "redis"
      version: "6.2.6"
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""

  repo:
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""

  server:
    autoscale:
      enabled: false
    service:
      type: NodePort
    resources: {}
      # limits:
      #   cpu: ""
      #   memory: ""
      # requests:
      #   cpu: ""
      #   memory: ""

  argocdVaultPlugin:
    enabled: true
    imageRegistry:
      host: "ghcr.io"
      repository: "gccloudone-aurora"
    image:
      name: "argocd-repo-server"
      version: "main"
    configMapName: "cmp-plugin"

    env:
      ARGOCD_ENV_AVP_TYPE: "" # azurekeyvault, awssecretsmanager, etc

      # # Azure
      # ARGOCD_ENV_AZURE_TENANT_ID: ""
      # ARGOCD_ENV_AZURE_CLIENT_ID: ""
      # ARGOCD_ENV_AZURE_CLIENT_SECRET: ""

      # # AWS
      # ARGOCD_ENV_AWS_REGION: ""

    azure:
      AADPodIdentity:
        enabled: false
        identityName: "argocd-vault-plugin"
        managedIdentity:
          clientID: ""
          resourceID: ""


register:
  clusters: {}
    # mgmt-dev-cc-00:
    #   server:
    #   token:
    #   caData:

  repositories: {}
    # aurora-helm:
    #   type: helm
    #   url: https://gccloudone-aurora.github.io/aurora-platform-charts
    # aurora-clusters:
    #   type: git
    #   url: https://github.com/gccloudone-aurora/aurora-template-example.git
    #   path: platform/clusters
    # aurora-namespaces:
    #   type: git
    #   url: https://github.com/gccloudone-aurora/aurora-template-example.git
    #   path: platform/namespaces

  repositoryCreds: {}
    # aurora-helm:
    #   type: helm
    #   url: https://gccloudone-aurora.github.io/aurora-platform-charts
    #   username: ""
    #   password: ""
    # aurora-clusters:
    #   type: git
    #   url: https://github.com/gccloudone-aurora/aurora-template-example.git
    #   username: ""
    #   password: ""
    # aurora-namespaces:
    #   type: git
    #   url: https://github.com/gccloudone-aurora/aurora-template-example.git
    #   username: ""
    #   password: ""

netpol:
  enabled: false
