{{ if .Values.components.loki.ruler.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-loki-alerts-cm"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "loki-alerts-cm"
        - name: HELM_VALUES
          value: |
            resources:
              - apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: loki-alerting-rules
                  labels:
                    app.kubernetes.io/part-of: loki-system
                    app.kubernetes.io/managed-by: argo
                    release: monitoring-metrics
                data:
                  rules.yaml: |
                    groups:
                    - name: watch-dog-alerts
                      rules:
                        - alert: WatchDogAlert
                          expr: vector(1)
                          for: 1m
                          labels:
                            severity: test
                          annotations:
                            message: "This alert always fires."
                            runbook: ""
                    - name: kube-bench-alerts
                      rules:
                      - alert: KubeBenchCheckDidNotPass
                        expr: |
                          count_over_time({namespace="kube-bench-system"} |~ "^\\[(FAIL|WARN)\\]"[5m]) > 0
                        for: 1m
                        labels:
                          severity: P1-Critical
                          scope: cluster
                        annotations:
                          message: "The kube-bench job reported that a check has not passed, it has either failed or displayed a warning."
                          runbook: ""

  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
